# -*- coding: utf-8 -*-
"""World_Bank.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14sOguxs4kd-7pXiJyFtbMX_u67aOSK9i
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,6))

pop = pd.read_excel("/content/population.xls")
gdp = pd.read_excel("/content/gdp.xls")

pop.head()

pop = pop.iloc[4:]
gdp = gdp.iloc[4:]

pop = pop.rename(columns={"Country Name": "Country"})
gdp = gdp.rename(columns={"Country Name": "Country"})

import pandas as pd

pop = pd.read_excel("/content/population.xls", header=None)
gdp = pd.read_excel("/content/gdp.xls", header=None)

pop.columns = pop.iloc[4]
gdp.columns = gdp.iloc[4]

pop = pop.iloc[5:]
gdp = gdp.iloc[5:]

pop.head()

pop = pop.rename(columns={"Country Name": "Country"})
gdp = gdp.rename(columns={"Country Name": "Country"})

print(pop.columns.tolist())

import pandas as pd

pop = pd.read_excel("/content/population.xls", header=3)
gdp = pd.read_excel("/content/gdp.xls", header=3)

print(pop.columns.tolist())

pop.columns = pop.columns.str.strip()
gdp.columns = gdp.columns.str.strip()

pop = pop.rename(columns={"Country Name": "Country"})
gdp = gdp.rename(columns={"Country Name": "Country"})

pop = pop.drop(columns=["Country Code", "Indicator Name", "Indicator Code"])
gdp = gdp.drop(columns=["Country Code", "Indicator Name", "Indicator Code"])

pop_long = pop.melt(id_vars=["Country"], var_name="Year", value_name="Population")
gdp_long = gdp.melt(id_vars=["Country"], var_name="Year", value_name="GDP")

pop_long["Year"] = pop_long["Year"].astype(int)
gdp_long["Year"] = gdp_long["Year"].astype(int)

data = pd.merge(pop_long, gdp_long, on=["Country", "Year"])
data.dropna(inplace=True)

data["GDP_per_capita"] = data["GDP"] / data["Population"]

world_pop = data.groupby("Year")["Population"].sum()

plt.figure(figsize=(10,6))
world_pop.plot()
plt.title("World Population Over Time")
plt.xlabel("Year")
plt.ylabel("Population")
plt.show()

world_gdp = data.groupby("Year")["GDP"].sum()

plt.figure(figsize=(10,6))
world_gdp.plot(color='green')
plt.title("World GDP Over Time")
plt.xlabel("Year")
plt.ylabel("GDP")
plt.show()

latest = data[data["Year"] == data["Year"].max()]
top_pop = latest.sort_values("Population", ascending=False).head(10)

sns.barplot(x="Population", y="Country", data=top_pop)
plt.title("Top 10 Most Populated Countries")
plt.show()

top_gdp = latest.sort_values("GDP", ascending=False).head(10)

sns.barplot(x="GDP", y="Country", data=top_gdp)
plt.title("Top 10 GDP Countries")
plt.show()

sns.scatterplot(x="Population", y="GDP", data=latest)
plt.title("GDP vs Population")
plt.show()

top_gdppc = latest.sort_values("GDP_per_capita", ascending=False).head(10)

sns.barplot(x="GDP_per_capita", y="Country", data=top_gdppc)
plt.title("Top 10 GDP per Capita")
plt.show()

sns.scatterplot(x="Population", y="GDP_per_capita", data=latest)
plt.title("Population vs GDP per Capita")
plt.show()

growth_pop = world_pop.pct_change()*100

growth_pop.plot()
plt.title("World Population Growth Rate (%)")
plt.show()

growth_gdp = world_gdp.pct_change()*100

growth_gdp.plot(color='red')
plt.title("World GDP Growth Rate (%)")
plt.show()

countries = ["United States", "China", "India"]
subset = data[data["Country"].isin(countries)]

sns.lineplot(x="Year", y="GDP_per_capita", hue="Country", data=subset)
plt.title("GDP per Capita Over Time")
plt.show()